### ISSUE TITLE
打捞到新船后，识别不了锁定新船的状态

### ISSUE THREAD

**Issue by useserver** [huan-yp/Auto-WSGR#12]
![image](https://user-images.githubusercontent.com/76869920/211541609-4e0c0c46-d3c2-4f7a-b4ff-cbd9c522e887.png)

ERROR 19:16:12 root] ===================ERROR===================
[ERROR 19:16:12 root] 匹配状态失败! state: get_ship  last_action: None
[ERROR 19:16:12 root] ====================END====================
[ERROR 19:16:12 root] ===================ERROR===================
[ERROR 19:16:12 root] Image Match Failed, Processing
[ERROR 19:16:12 root] ====================END====================
[ERROR 19:16:19 root] ===================ERROR===================
[ERROR 19:16:19 root] 匹配状态失败! state: get_ship  last_action: None
[ERROR 19:16:19 root] ====================END====================

**Comment by useserver** [comment]
报错信息：
Traceback (most recent call last):
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\common.py", line 332, in update_state
    self.Info.update_state()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\common.py", line 169, in update_state
    raise ImageNotFoundErr()
AutoWSGR.constants.custom_exceptions.ImageNotFoundErr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\auto_daily.py", line 6, in <module>
    operation.run()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\daily_api.py", line 51, in run
    ret = plan.run()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\common.py", line 298, in run
    return self.fight()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\common.py", line 251, in fight
    ret = self._make_decision()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\normal_fight.py", line 260, in _make_decision
    state = self.update_state()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\common.py", line 344, in update_state
    self.Info.update_state()
  File "C:\Users\wuwuopen\PycharmProjects\Auto-WSGR\AutoWSGR\fight\common.py", line 169, in update_state
    raise ImageNotFoundErr()
AutoWSGR.constants.custom_exceptions.ImageNotFoundErr

另外刷决战也有同样问题，决战的报错：
Traceback (most recent call last):
  File "C:\PycharmProjects\Auto-WSGR\examples\decisive_battle.py", line 10, in <module>
    decisive_battle.start_fight()
  File "C:\PycharmProjects\Auto-WSGR\AutoWSGR\fight\decisive_battle.py", line 484, in start_fight
    self.enter_map(False)
  File "C:\PycharmProjects\Auto-WSGR\AutoWSGR\fight\decisive_battle.py", line 385, in enter_map
    self.detect()
  File "C:\PycharmProjects\Auto-WSGR\AutoWSGR\fight\decisive_battle.py", line 274, in detect
    return _res[res]
TypeError: list indices must be integers or slices, not NoneType

**Comment by huan-yp** [comment]
首先请检查一下分辨率配置是否正确（1280*960)。
如果可能，请提供完整的日志文件，日志文件位于工作目录下 log 文件夹。

**Comment by useserver** [comment]
![image](https://user-images.githubusercontent.com/76869920/211571134-3cf3930a-044e-481c-9ab3-3c8aad54d8d4.png)
分辨率是1280*720 没有问题
日志：https://cowtransfer.com/s/a23807d460c146

**Comment by huan-yp** [comment]
新船锁定的问题手上没账号测不了。
决战的话，首先是只支持 E5,E6，另外需要先手动打一遍才能用，看上去是进决战之后图片识别失败了，你可以用 default_setting_debug.yaml 再试一次把log发一下

**Comment by useserver** [comment]
![image](https://user-images.githubusercontent.com/76869920/211807812-98f6e0c8-ba55-4017-a4d8-6b5af125d737.png)

日志：https://cowtransfer.com/s/afc2ab7eb5ca41
控制台输出：https://cowtransfer.com/s/5dacc8d67fc14b
又打了一次e5，获得新船后出了同样的错
电脑是台式机，cpu是amd5600x+16g内存，模拟器不卡顿，性能应该不是瓶颈

**Comment by Nickydusk** [comment]
已经在最新版本尝试修复，你可以用以下命令更新后再试试，如果没问题的话该修改将在下个稳定版推送。
```
pip install -U git+https://github.com/huan-yp/Auto-WSGR.git@main
```

**Comment by useserver** [comment]
![QQ截图20230114185728](https://user-images.githubusercontent.com/76869920/212470621-df1348ca-a262-4f22-8f71-c5b45c3581c8.png)

新版本更新后刷常规图不会卡在锁船界面，刷决战e6可以点击锁定舰船，但是延迟很大，导致获得的5搜船没点完，无法进入下个界面并报错

**Comment by huan-yp** [comment]
能提供相应的运行日志吗？

**Comment by useserver** [comment]
![image](https://user-images.githubusercontent.com/76869920/212551868-c72bcb82-3960-476b-be37-2edbff557b07.png)
log文件夹下没有详细日志内容，控制台输出的内容忘记保存了。。我的号现在决战也没有新船能new了，不能复现这个bug了
