### ISSUE TITLE
9-1炸鱼出新船后出现报错

### ISSUE THREAD

**Issue by yyl893653496** [huan-yp/Auto-WSGR#14]
报错如下

[ERROR 18:38:06 root] ===================ERROR===================
[ERROR 18:38:06 root] 匹配状态失败! state: get_ship  last_action: None
[ERROR 18:38:06 root] ====================END====================
[ERROR 18:38:06 root] ===================ERROR===================
[ERROR 18:38:06 root] Image Match Failed, Processing
[ERROR 18:38:06 root] ====================END====================
[ERROR 18:38:14 root] ===================ERROR===================
[ERROR 18:38:14 root] 匹配状态失败! state: get_ship  last_action: None
[ERROR 18:38:14 root] ====================END====================
Traceback (most recent call last):
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\common.py", line 332, in update_state
    self.Info.update_state()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\common.py", line 169, in update_state
    raise ImageNotFoundErr()
AutoWSGR.constants.custom_exceptions.ImageNotFoundErr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/SilverLuxury/AutoWSGR-0.0.9/examples/auto_daily.py", line 8, in <module>
    operation.run()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\daily_api.py", line 51, in run
    ret = plan.run()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\common.py", line 298, in run
    return self.fight()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\common.py", line 251, in fight
    ret = self._make_decision()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\normal_fight.py", line 260, in _make_decision
    state = self.update_state()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\common.py", line 344, in update_state
    self.Info.update_state()
  File "E:\SilverLuxury\AutoWSGR-0.0.9\AutoWSGR\fight\common.py", line 169, in update_state
    raise ImageNotFoundErr()
AutoWSGR.constants.custom_exceptions.ImageNotFoundErr

进程已结束,退出代码1

**Comment by huan-yp** [comment]
导致该问题的原因是部分操作出现失败，程序流程继续进行但游戏画面未继续进行。目前还没有完全解决该问题，你可以自行捕获异常并重启任务以暂时避免该问题。

该问题会在以后尝试解决。

**Comment by Nickydusk** [comment]
看起来和上一个issue情况是一样的，我们当时已经尝试解决了，你的脚本版本更新到最新了吗？ #12

**Comment by yyl893653496** [comment]
我是直接在GitHub上下载压缩包的，版本应该是最新的

**Comment by huan-yp** [comment]
重构后应该修好了 https://github.com/huan-yp/Auto-WSGR/commit/680aa45e488285dc3fecb381139b368a5b877090
