### ISSUE TITLE
在完成战役切换至出征时遇到问题

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#23]
Traceback (most recent call last):
  File "auto_daily.py", line 5, in <module>
    operation.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\scripts\daily_api.py", line 46, in run
    ret = plan.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\common.py", line 338, in run
    ret = self._enter_fight(same_work)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 231, in _enter_fight
    self._change_fight_map(self.chapter, self.map)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 465, in _change_fight_map
    self._move_map(map, chapter)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 444, in _move_map
    raise ImageNotFoundErr("unknown reason can't find number image" + str(target_map))
AutoWSGR.constants.custom_exceptions.ImageNotFoundErr: unknown reason can't find number image4

意思是在章节切换完成前就开始切换地图导致的

**Comment by huan-yp** [comment]
fixed https://github.com/huan-yp/Auto-WSGR/commit/4f921a51bcf8f930f8d6d496f9d9d970c52f592d
