### ISSUE TITLE
adb里的错误（？）

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#39]
```python
Traceback (most recent call last):
  File "e:\Python\Python39\Lib\site-packages\autowsgr\auto_daily.py", line 5, in <module>
    operation = DailyOperation(f"{os.path.dirname(os.path.abspath(__file__))}/user_settings.yaml")
  File "E:\Python\Python39\lib\site-packages\autowsgr\scripts\daily_api.py", line 19, in __init__
    self.timer = start_script(setting_path)
  File "E:\Python\Python39\lib\site-packages\autowsgr\scripts\main.py", line 40, in start_script
    timer = Timer(config, logger)
  File "E:\Python\Python39\lib\site-packages\autowsgr\controller\run_timer.py", line 66, in __init__
    self.init()
  File "E:\Python\Python39\lib\site-packages\autowsgr\controller\run_timer.py", line 76, in init
    self.start_game()
  File "E:\Python\Python39\lib\site-packages\autowsgr\controller\run_timer.py", line 101, in start_game
    self.Android.start_app(self.which_app)
  File "E:\Python\Python39\lib\site-packages\autowsgr\controller\android_controller.py", line 41, in start_app
    self.dev.start_app(package_name)
  File "E:\Python\Python39\lib\site-packages\airtest\core\android\android.py", line 328, in start_app
    return self.adb.start_app(package, activity)
  File "E:\Python\Python39\lib\site-packages\airtest\core\android\adb.py", line 1425, in start_app
    ret = self.shell(['monkey', '-p', package, '-c', 'android.intent.category.LAUNCHER', '1'])
  File "E:\Python\Python39\lib\site-packages\airtest\core\android\adb.py", line 409, in shell
    out = self.raw_shell(cmd)
  File "E:\Python\Python39\lib\site-packages\airtest\core\android\adb.py", line 367, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "E:\Python\Python39\lib\site-packages\airtest\core\android\adb.py", line 214, in cmd
    proc = self.start_cmd(cmds, device)
  File "E:\Python\Python39\lib\site-packages\airtest\core\android\adb.py", line 182, in start_cmd
    LOGGING.debug(" ".join(cmds))
TypeError: sequence item 6: expected str instance, method found
```

最近重新装了一下python，然后就遇到了这个问题
发生在在模拟器启动之后，打开舰R之前

**Comment by cwlm** [comment]
如果提前把舰R打开似乎是可以正常运行的

**Comment by veadex** [comment]
> 如果提前把舰R打开似乎是可以正常运行的

找到了，发布的时候只只测试了打开游戏的情况，没注意函数有问题

**Comment by cwlm** [comment]
以前3.7.9的python好像是没问题的？

**Comment by veadex** [comment]
是我昨天推的内容有问题，我晚会会改一下
