### ISSUE TITLE
读取舰船费用出错

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#40]
```python
Traceback (most recent call last):
  File "e:\Python\Python39\Lib\site-packages\autowsgr\decisive_battle.py", line 14, in <module>
    decisive_battle.start_fight()
  File "E:\Python\Python39\lib\site-packages\autowsgr\fight\decisive_battle.py", line 526, in start_fight
    res = self.fight()
  File "E:\Python\Python39\lib\site-packages\autowsgr\fight\decisive_battle.py", line 504, in fight
    res = self._before_fight()
  File "E:\Python\Python39\lib\site-packages\autowsgr\fight\decisive_battle.py", line 454, in _before_fight
    self.choose()  # 获取战备舰队
  File "E:\Python\Python39\lib\site-packages\autowsgr\fight\decisive_battle.py", line 341, in choose
    return self.choose(True)
  File "E:\Python\Python39\lib\site-packages\autowsgr\fight\decisive_battle.py", line 325, in choose
    if int(cost[1][1:]) > self.stats.score:
ValueError: invalid literal for int() with base 10: ''
```

![Screenshot_20231130-042648](https://github.com/huan-yp/Auto-WSGR/assets/105329086/75347a2f-daca-40c9-8241-755d68ce174e)

似乎没法复现，我截图下来用recognize_number可以读出来

```python
import cv2
from autowsgr.ocr.ship_name import _recognize_ship, recognize_number

screen = cv2.imread('Screenshot_20231130-042648.png')
costs = recognize_number(screen[550:585, 245:1031], "x")
for i, cost in enumerate(costs):
    print(i)
    print(cost[1])
```

```bash
6
True
6
True
12
True
6
True
3
True
```

**Comment by cwlm** [comment]
请问还有其他可能原因吗

**Comment by veadex** [comment]
记录
当全黑时读取会报错
截图不报错可能是因为分辨率高的原因
![image](https://github.com/huan-yp/Auto-WSGR/assets/65024689/cf77fce3-d0ff-4433-bb73-7e715f5bd0d6)
以下是1280*960分辨率的图片
![1](https://github.com/huan-yp/Auto-WSGR/assets/65024689/1980a018-324a-423f-ba1a-324b32e60ad6)

**Comment by veadex** [comment]
确实是这样，最后的加护没有识别出来，导致报错
![image](https://github.com/huan-yp/Auto-WSGR/assets/65024689/2cf8fe2f-b9e0-42aa-b3b6-679d103ebc26)
![2](https://github.com/huan-yp/Auto-WSGR/assets/65024689/8dcfbbaa-191e-42c1-b95e-99b70041a8b6)
