### ISSUE TITLE
每次大退SL后都会遇到critical error

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#7]
打9-1B点时遇到的问题，错误如下

[INFO 11:27:37 root] List of devices attached
[INFO 11:27:37 root] emulator-5554          device product:PCRT00 model:PCRT00 device:star2qltechn transport_id:1

正在 Ping baidu.com [110.242.68.66] 具有 32 字节的数据:
来自 110.242.68.66 的回复: 字节=32 时间=46ms TTL=48
来自 110.242.68.66 的回复: 字节=32 时间=35ms TTL=48
来自 110.242.68.66 的回复: 字节=32 时间=47ms TTL=48
来自 110.242.68.66 的回复: 字节=32 时间=38ms TTL=48

110.242.68.66 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 35ms，最长 = 47ms，平均 = 41ms
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\controller\run_timer.py", line 144, in start_game
    if self.everyday_check:
AttributeError: 'Timer' object has no attribute 'everyday_check'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\controller\run_timer.py", line 162, in restart
    self.start_game(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\controller\run_timer.py", line 155, in start_game
    raise BaseException("fail to start game")
BaseException: fail to start game

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AutoDaily.py", line 6, in <module>
    operation.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\daily_api.py", line 55, in run
    self._normal_fight_once(task_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\daily_api.py", line 40, in _normal_fight_once
    ret = plan.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\common.py", line 255, in run
    return self._fight()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\common.py", line 292, in _fight
    self.SL()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\common.py", line 304, in SL
    self.timer.restart()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\controller\run_timer.py", line 179, in restart
    raise CriticalErr("CriticalErr on restart function")
AutoWSGR.constants.custom_exceptions.CriticalErr: CriticalErr on restart function

**Comment by Nickydusk** [comment]
感谢反馈，这是一个bug，将尽快修复。你可以在源码里把这个判断逻辑注释掉来暂时屏蔽此问题

**Comment by cwlm** [comment]
谢谢

**Comment by huan-yp** [comment]
Bug fixed on github，It will release on pypi soon
