### ISSUE TITLE
安装完之后报错，第一次运行报错

### ISSUE THREAD

**Issue by linhaiwen** [huan-yp/Auto-WSGR#73]
Error: Can not import paddle core while this file exists: C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\base\libpaddle.pyd
Traceback (most recent call last):
  File "C:\Users\45047\Documents\Auto-WSGR-main\examples\auto_daily.py", line 6, in <module>
    operation = DailyOperation(
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\scripts\daily_api.py", line 16, in __init__
    self.timer = start_script(setting_path)
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\scripts\main.py", line 76, in start_script
    timer = Timer(config, logger)
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\timer\timer.py", line 59, in __init__
    self.ocr_backend = PaddleOCRBackend(config, logger)
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\timer\backends\ocr_backend.py", line 352, in __init__
    from paddleocr import PaddleOCR
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\base\__init__.py", line 36, in <module>
    from . import core
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\base\core.py", line 380, in <module>
    raise e
  File "C:\Users\45047\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\base\core.py", line 268, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: 找不到指定的模块。

**Comment by huan-yp** [comment]
临时解决方案：user_settings.yaml 中 ocr_backend 参数改为 "easyocr"

**Comment by linhaiwen** [comment]
可以了。但是这个问题要怎么解决呢？

**Comment by huan-yp** [comment]
1. 检查 Windows 病毒防护日志，确定是否有 .dll 文件被误删。
2. 检查 Python 环境，确认是否有库与 paddlepaddle 冲突。
3. 重新安装各项依赖。

如果解决不了可以就用 easyocr，这不会影响脚本功能。
