### ISSUE TITLE
地图识别以及道中资源点收集BUG

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#9]
打7-4时遇到的问题，划到7-1后报错

Traceback (most recent call last):
  File "AutoDaily.py", line 6, in <module>
    operation.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\daily_api.py", line 55, in run
    self._normal_fight_once(task_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\daily_api.py", line 40, in _normal_fight_once
    ret = plan.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\common.py", line 252, in run
    enter_ret = self._enter_fight(same_work)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 231, in _enter_fight
    self._change_fight_map(self.chapter, self.map)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 451, in _change_fight_map
    self._move_node(map_id, chapter_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 408, in _move_node
    NowNode = self._get_node(chapter)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 336, in _get_node
    raise TimeoutError("can't verify map")
TimeoutError: can't verify map

另外，由于出门点没有补给，supply_ship_mode能否不判断ABC点

**Comment by huan-yp** [comment]
感谢BUG反馈，将在不久后修复。
关于补给舰的问题，supply_ship_mode 是为快速使用设计的。
请使用 enemy_rules 编辑高级规则，其中带战利品的补给舰名为 `SAP`，常规补给舰为 `NAP`。
如果对 enemy_rules 的使用有疑问，请新开一个 issue 讨论。

**Comment by cwlm** [comment]
谢谢

**Comment by cwlm** [comment]
进入这种点后无法前进，请问如何解决，谢谢
![image](https://user-images.githubusercontent.com/105329086/210125807-ceac58e6-04f1-4bb3-820d-73051dbbaa98.png)

**Comment by huan-yp** [comment]
如果可以的话，请启用调试模式复现一下并提供 log 信息以帮助排查问题，（将 logger 设置全部改为 True）

**Comment by cwlm** [comment]
对不起，请问log在哪里打开

**Comment by huan-yp** [comment]
不知道的话就算了，以后会写文档，我慢慢排查问题吧。

**Comment by huan-yp** [comment]
Bug Fixed.
